### ISSUE TITLE
Is there any helper functions to visualize the predicted trajectories & gt ?

### ISSUE THREAD

**Issue by sean-wade** [Tsinghua-MARS-Lab/ViP3D#12]
I want to visualize the predicted trajs. But I cannot find any code in your repo.
So is there any way to visualize it on the bev images?

Maybe nuscenes has the render function (I'm not familar.)?

Thanks for reply.

**Comment by GentleSmile** [comment]
We have not released the visualization code because the tool is complicated to deploy. To visualize only predicted and gt trajectories on bev images is easy. Predicted trajectories have been obtained [here](https://github.com/Tsinghua-MARS-Lab/ViP3D/blob/c4a60b01a4b5d68289c1958d2e6935ed73d76964/plugin/vip3d/models/vip3d.py#L978), and gt trajectories are obtained [here](https://github.com/Tsinghua-MARS-Lab/ViP3D/blob/c4a60b01a4b5d68289c1958d2e6935ed73d76964/plugin/vip3d/models/vip3d.py#L949).

**Comment by sean-wade** [comment]
Thanks for reply. I just don't know how to render the trajectories on the map of nuscenes. Is there any way to do it?

**Comment by GentleSmile** [comment]
For map information, we have [lanes ](https://github.com/Tsinghua-MARS-Lab/ViP3D/blob/c4a60b01a4b5d68289c1958d2e6935ed73d76964/plugin/vip3d/models/vip3d.py#L998)that have been normalized to the ego coordinate system. You may refer to 
a simple rendering function [here ](https://github.com/Tsinghua-MARS-Lab/DenseTNT/blob/294596b0b141fb7b18248889e5c409630c5f7ed6/src/utils.py#L574)in our another repository.

**Comment by sean-wade** [comment]
OK, thanks! I'll try it.
